seo:
  title: XRP Ledger Developer Portal
  description: The best API documentation generator ever.
  siteUrl: https://xrpl-docs.redoc.ly/developer-portal/
  keywords: XRP Ledger developer portal, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
    IgnoreInternalEmptyHash: true
logo:
  image: ./static/img/XRPLedger_DevPortal-white.svg
  altText: XRP Ledger Developer Portal
  height: 40px
  width: 162px
toc:
  enable: true
editPage:
  baseUrl: https://github.com/amarantha-k/xrpl-org-dev-portal/tree/master/
  icon: ./images/pencil.svg
copyCodeSnippet:
  enable: true
  buttonText: Copy
  tooltipText: Copy the code snippet
  toasterText: Copied!
  toasterDuration: 1500
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
  - ./static/css/devportal2022-v4.css
  - ./static/vendor/fontawesome/css/font-awesome.min.css
  - ./static/css/fixes.css

#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1

postBodyScripts:
  - ./static/js/xrpl-2.2.0.min.js
  - ./static/js/jquery-3.6.0.min.js
  - ./static/vendor/bootstrap.min.js

# Top Menu Navigation ----------------------------------------------------------
## NOTE: This is ignored. Our custom top nav uses top-nav.yaml instead.
nav:
  - search: true

# Footer configuration ---------------------------------------------------------
footer:
  copyrightText: Copyright Â© 2022 XRP Ledger.
  columns:
    - group: About
      items:
        - page: about/xrp-ledger-overview.mdx
        - page: about/use-cases.mdx
        - page: about/history.mdx
        - label: Ledger Explorer
          link: https://livenet.xrpl.org/
        - page: about/xrp-overview.mdx
        - page: about/impact.mdx
        - label: XRPL Foundation
          link: https://foundation.xrpl.org/
        - page: about/faq.mdx
    - group: Docs
      items:
        - page: docs/index.md
        - page: docs/concepts/introduction/intro-to-xrpl.md
        - page: docs/tutorials/index.md
        - page: docs/references/index.mdx
        - page: docs/code-samples/index.mdx
        - page: docs/dev-tools/index.md
    - group: Community
      items:
        - page: community/index.mdx
        - page: community/contribute-code.md
        - page: community/events.mdx
        - page: community/ambassadors.mdx
        - label: XRPL Jobs
          link: https://jobs.xrpl.org/
        - label: Dev Blog
          page: blog/index.md
        - label: GitHub
          link: https://github.com/XRPLF/
        - page: community/report-a-scam.md
